sonar.projectKey=licit-ui-commands
sonar.sourceEncoding=UTF-8
# only analyzing actual library source
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
# tell sonar where to find coverage results
sonar.javascript.lcov.reportPaths=coverage/lcov.info

#sonar.dependencyCheck.jsonReportPath=dependency-check-reports/dependency-check-report.json
#debug
#sonar.dependencyCheck.htmlReportPath=dependency-check-reports/dependency-check-report.html
