# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [pipeline/test]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # extra info for sonar
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        env: 
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TEST }}
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm whoami # Verify token works
        name: Verify token
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: npm-logs
          path: /home/moot/.npm/_logs

      - run: npm ci
      - run: npm run lint
      - run: npm run ci:build
      - run: npm run test:coverage

      # Sonar scan. https://github.com/marketplace/actions/sonarqube-scan
      - run: echo "TAG=$(npm pkg get version --workspaces=false | tr -d \")" >> "$GITHUB_ENV" # Get Version number
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectVersion=$TAG
      # Sonar verify https://github.com/marketplace/actions/sonarqube-quality-gate-check
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
