# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ESS-721]

  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to run on'
        required: true
        default: 'main'

  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        #with:
        #  fetch-depth: 0 # extra info for sonar
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm whoami
      - run: npm ci
      - run: npm run lint
      - run: npm run ci:build
      - run: npm run test:coverage
