# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [pipeline/test]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # extra info for sonar
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        env: 
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: ${{ matrix.node-version }}

      #- run: npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
      #- run: npm whoami # Verify token. Remove this line

      - run: npm ci
      - run: npm run lint
      - run: npm run ci:build
      - run: npm run test:coverage

      # Dependency-Check
      - run: npx owasp-dependency-check --scan . --suppression suppression.xml --nvdApiKey ${{ secrets.NVD_KEY }} --disableYarnAudit --exclude node_modules/node-gyp/**/* --exclude dependency-check-bin/**/* 
      # Sonar scan. https://github.com/marketplace/actions/sonarqube-scan
      - run: echo "{TAG}={$(npm pkg get version --workspaces=false | tr -d \")}" >> "$GITHUB_ENV" # Get Version number
      - run: echo $TAG #DEBUG
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          #SONAR_PROJECT_VERSION: 0
      # Sonar verify https://github.com/marketplace/actions/sonarqube-quality-gate-check
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
